version: '3.8'

services:
  # Development API service with hot reload
  sleeper-api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: sleeper-api-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_PATH=/app/data/database.sqlite
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - api_data:/app/data
    ports:
      - "3000:3000"
    networks:
      - sleeper_network
    command: npm run dev

  # Development nginx (simplified)
  nginx:
    image: nginx:alpine
    container_name: sleeper-nginx-dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sleeper_network
    depends_on:
      - sleeper-api

volumes:
  api_data:
    driver: local

networks:
  sleeper_network:
    driver: bridge
